# Generated by Django 3.0.8 on 2021-08-08 21:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20210623_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitem',
            old_name='service',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='division',
            field=models.CharField(blank=True, choices=[('BD-C*', 'Dhaka City'), ('BD-O*', 'Outside Dhaka City')], max_length=9),
        ),
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
