# Generated by Django 3.0.8 on 2021-08-08 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20210809_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='description',
        ),
    ]
