# Generated by Django 3.0.8 on 2021-08-08 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_remove_lineitem_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='division',
            new_name='area',
        ),
    ]
