# Generated by Django 3.0.8 on 2021-08-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20210809_0418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='message',
            field=models.TextField(blank=True, default='this is a default message.'),
        ),
    ]
